name: riscv-tests
run-name: Run riscv-tests@verilator

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  ui-p:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: ./.github/actions/install-veryl
      - uses: ./.github/actions/install-verilator
      - name: Build
        run: make build
      - name: Test
        run: cd test && python3 riscv-tests.py ui-p-
